///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace my_sample_testsuite
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the my_sample_testsuiteRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    [RepositoryFolder("40b2f5e2-9ffb-4169-8a12-6cc210e99ee3")]
    public partial class my_sample_testsuiteRepository : RepoGenBaseFolder
    {
        static my_sample_testsuiteRepository instance = new my_sample_testsuiteRepository();
        my_sample_testsuiteRepositoryFolders.MyStoreAppFolder _mystore;

        /// <summary>
        /// Gets the singleton class instance representing the my_sample_testsuiteRepository element repository.
        /// </summary>
        [RepositoryFolder("40b2f5e2-9ffb-4169-8a12-6cc210e99ee3")]
        public static my_sample_testsuiteRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public my_sample_testsuiteRepository() 
            : base("my_sample_testsuiteRepository", "/", null, 0, false, "40b2f5e2-9ffb-4169-8a12-6cc210e99ee3", ".\\RepositoryImages\\my_sample_testsuiteRepository40b2f5e2.rximgres")
        {
            _mystore = new my_sample_testsuiteRepositoryFolders.MyStoreAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("40b2f5e2-9ffb-4169-8a12-6cc210e99ee3")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MyStore folder.
        /// </summary>
        [RepositoryFolder("e9b3f319-229d-40c2-91fe-31c08c681527")]
        public virtual my_sample_testsuiteRepositoryFolders.MyStoreAppFolder MyStore
        {
            get { return _mystore; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
    public partial class my_sample_testsuiteRepositoryFolders
    {
        /// <summary>
        /// The MyStoreAppFolder folder.
        /// </summary>
        [RepositoryFolder("e9b3f319-229d-40c2-91fe-31c08c681527")]
        public partial class MyStoreAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _logintoyourcustomeraccountInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _passwdInfo;
            RepoItemInfo _spantagsigninInfo;
            RepoItemInfo _logmeoutInfo;

            /// <summary>
            /// Creates a new MyStore  folder.
            /// </summary>
            public MyStoreAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyStore", "/dom[7]", parentFolder, 30000, null, false, "e9b3f319-229d-40c2-91fe-31c08c681527", "")
            {
                _logintoyourcustomeraccountInfo = new RepoItemInfo(this, "LogInToYourCustomerAccount", ".//header[#'header']/div[2]//nav/?/?/a[@innertext='Sign in']", 30000, null, "4e8430f4-0c48-49c5-94cb-d456eebfdd03");
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'email']", 30000, null, "8fc936af-d147-4118-8874-bf4cc464f7ae");
                _passwdInfo = new RepoItemInfo(this, "Passwd", ".//input[#'passwd']", 30000, null, "3ae02310-bfcf-418e-a3b9-07d4544379fe");
                _spantagsigninInfo = new RepoItemInfo(this, "SpanTagSignIn", ".//button[#'SubmitLogin']/span[@innertext='Sign in']", 30000, null, "11169937-de4b-4d7a-9d8d-b69329c71aa8");
                _logmeoutInfo = new RepoItemInfo(this, "LogMeOut", ".//header[#'header']//nav/div[2]/a[@innertext='Sign out']", 30000, null, "f4cfd0ca-91ad-4cd9-a1ea-26a1e983da72");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e9b3f319-229d-40c2-91fe-31c08c681527")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e9b3f319-229d-40c2-91fe-31c08c681527")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LogInToYourCustomerAccount item.
            /// </summary>
            [RepositoryItem("4e8430f4-0c48-49c5-94cb-d456eebfdd03")]
            public virtual Ranorex.ATag LogInToYourCustomerAccount
            {
                get
                {
                    return _logintoyourcustomeraccountInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogInToYourCustomerAccount item info.
            /// </summary>
            [RepositoryItemInfo("4e8430f4-0c48-49c5-94cb-d456eebfdd03")]
            public virtual RepoItemInfo LogInToYourCustomerAccountInfo
            {
                get
                {
                    return _logintoyourcustomeraccountInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("8fc936af-d147-4118-8874-bf4cc464f7ae")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("8fc936af-d147-4118-8874-bf4cc464f7ae")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The Passwd item.
            /// </summary>
            [RepositoryItem("3ae02310-bfcf-418e-a3b9-07d4544379fe")]
            public virtual Ranorex.InputTag Passwd
            {
                get
                {
                    return _passwdInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Passwd item info.
            /// </summary>
            [RepositoryItemInfo("3ae02310-bfcf-418e-a3b9-07d4544379fe")]
            public virtual RepoItemInfo PasswdInfo
            {
                get
                {
                    return _passwdInfo;
                }
            }

            /// <summary>
            /// The SpanTagSignIn item.
            /// </summary>
            [RepositoryItem("11169937-de4b-4d7a-9d8d-b69329c71aa8")]
            public virtual Ranorex.SpanTag SpanTagSignIn
            {
                get
                {
                    return _spantagsigninInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagSignIn item info.
            /// </summary>
            [RepositoryItemInfo("11169937-de4b-4d7a-9d8d-b69329c71aa8")]
            public virtual RepoItemInfo SpanTagSignInInfo
            {
                get
                {
                    return _spantagsigninInfo;
                }
            }

            /// <summary>
            /// The LogMeOut item.
            /// </summary>
            [RepositoryItem("f4cfd0ca-91ad-4cd9-a1ea-26a1e983da72")]
            public virtual Ranorex.ATag LogMeOut
            {
                get
                {
                    return _logmeoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogMeOut item info.
            /// </summary>
            [RepositoryItemInfo("f4cfd0ca-91ad-4cd9-a1ea-26a1e983da72")]
            public virtual RepoItemInfo LogMeOutInfo
            {
                get
                {
                    return _logmeoutInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}